USE [master]
GO
CREATE LOGIN [accbook] WITH PASSWORD=N'123456kK', DEFAULT_DATABASE=[AccountingBookDB], DEFAULT_LANGUAGE=[русский], CHECK_EXPIRATION=ON, CHECK_POLICY=ON
GO

ALTER LOGIN [accbook] ENABLE
GO

ALTER SERVER ROLE [sysadmin] ADD MEMBER [accbook]
GO


